### ISSUE TITLE
Adding Module to ActivityComponent

### ISSUE THREAD

**Issue by jemshit** [trevjonez/Dagger2-MultiBinding-Android-Example#2]
How do we add Module to `ActivityComponent`? Like some `ActivityComponent` needs `ActivityModule`, but some does not (like on this repo)

**Comment by trevjonez** [comment]
You just add it to the `ActivityComponent` then add a method to set it on the builder class

```java
@Subcomponent(modules = {MainActivityModule.class})
@MainActivityScope
public interface MainActivityComponent extends PlainComponent<MainActivity> {

    @Subcomponent.Builder
    interface Builder extends ActivityComponentBuilder<MainActivity, MainActivityComponent> {
        Builder module(MainActivityModule module);
    }
}
```

At this point the code in your activity that builds the component becomes:

```java
    component = ((ActivityComponentBuilderHost) getApplication()).getComponentBuilder(MainActivity.class, MainActivityComponent.Builder.class)
                                                                 .module(new MainActivityModule(this))
                                                                 .build();
    component.inject(this);
```

**Comment by jemshit** [comment]
Thanks, what if i add 'Builder module(MainActivityModule module)' into
ActivityComponentBuilder itself, any drawbacks you see?

**Comment by trevjonez** [comment]
Biggest draw back is you force that specific module on every component builder that extends the `ActivityComponentBuilder` interface. 

You might consider adding a third generic to `ActivityComponentBuilder` to force people to define a module for their activity:
```java
public interface ActivityComponentBuilder<ActivityType extends Activity, ComponentType extends PlainComponent<ActivityType>, ModuleType> {
    ActivityComponentBuilder<ActivityType, ComponentType, ModuleType> module(ModuleType module);
    ComponentType build();
}
```
however you can see that it quickly gets messy. the module method loses the strong type of the builder interface which could be fixed with a fourth generic property which would convert the signature to something like this:
```java
public interface ActivityComponentBuilder<ActivityType extends Activity, ComponentType extends PlainComponent<ActivityType>, ModuleType, Self extends ActivityComponentBuilder<ActivityType, ComponentType, ModuleType, Self>> {
    Self module(ModuleType module);
    ComponentType build();
}
```

So you can keep the strong typing we had before but it just makes the signature of everything messy and in practice you won't gain much of anything from doing it that way.
The only reason we defined these interfaces to begin with is so we can inject a `Map` of them into the Application.

Plus in my experience(migrating a large app and small app from no DI to dagger2) not every activity component has initially needed a module thus arguably this breaks the [interface segregation principal](https://en.wikipedia.org/wiki/Interface_segregation_principle)

**Comment by jemshit** [comment]
ok thanks :+1:
