### ISSUE TITLE
Different type of SubComponent implementation

### ISSUE THREAD

**Issue by jemshit** [trevjonez/Dagger2-MultiBinding-Android-Example#4]
Hi again, what kind of approach should we use for implementing other types of SubComponents than Activity ? Example, UserComponent needs to be SubComponent of ApplicationComponent.

I am thinking something like this:
```java
@UserScope
@Subcomponent(modules = UserComponent.UserModule.class)
public interface UserComponent { 

    @Subcomponent.Builder
    interface Builder extends UserComponentBuilder<UserComponent> {
        UserComponent.Builder userModule(UserComponent.UserModule module);
    }

    @Module
    class UserModule {
        @Provides @UserScope
        public UserModel provideUser(){
            return new UserModel();
        }
    }
}

public interface UserComponentBuilder<ComponentType> {
    ComponentType build();
}

```
Then *Application* class injects *UserComponent*, holds reference to *UserComponent*, so any class needs *UserComponent* will get it through *Application*, and if user logs out, that class will make *UserComponent* null (**reason is UserComponent should be Singleton throughout User lifecycle (from user signs in to logs out)**).  

Problems:
1) *UserComponent* does not extend PlainComponent because different types of classes other than *Activity* may inject it. So every class needs inject method declaration in *UserComponent*. What can we do about this? (maybe extends PlainComponent<Object> ?) 
2) Do i need here all *UserComponentBuilder* ? Since there will be only 1 type of UserComponentBuilder

Another example would be *Fragment* being SubComponent of *Activity*. Do we need all *FragmentComponentBuilder*, *FragmentComponentBuilderHost*, *ActivityScopeFragmentBinder*  ? And who really implements *FragmentComponentBuilderHost*?

Thanks

**Comment by trevjonez** [comment]
In the apps i work on for the user component I chose to skip doing a builder class and base type since there will only be one. Primary reason for the base builder type is to enable multibinding them into a map.

I would draw up an interface something like this to expose the functionality of managing the user component

```java
public interface UserComponentManager {
    void createUserComponent(/* args required to create user component. id of member? */);
    void dropUserComponent();
    UserComponent getUserComponent();
}
```

from there I do an abstract binding module for activity builders for each of the primary scopes. [like this](https://github.com/trevjonez/Dagger2-MultiBinding-Android-Example/blob/master/app/src/main/java/com/trevjonez/daggertest/application/AppScopeActivityBinder.java)

For the fragment related components it is just as you describe. Begin with defining a `FragmentComponentBuilder` and `FragmentComponentBuilderHost` interface(s). The point of implementation for the `FCBH` depends on the lifetime of your fragment. I personally don't use persisted fragments so my implementation point is usually on the `Activity` that the fragment exists inside of.

Also worth mentioning that since fragments are commonly reusable by many different activities it can be nice to define a fragment specific binding module such as:
```java
@Module(subcomponents = ImagePickerFragmentComponent.class)
public abstract class ImagePickerFragmentBinder {
    @Binds
    @IntoMap
    @FragmentKey(ImagePickerFragment.class)
    abstract FragmentComponentBuilder bindBuilder(ImagePickerFragmentComponent.Builder impl);
}
```

Then on the activity component of the activity to host the fragment just include the binder in the list of modules. This will enable you to inject `Map<Class<? extends Fragment>, Provider<FragmentComponentBuilder>>` in the activity class which will be used to implement the `FCBH` interface.

The last thing is how to handle lookup of the different `ACB` from the applications `getComponentBuilder` method. For this you can add a method on the user component such as: 
```java
    Map<Class<? extends Activity>, Provider<ActivityComponentBuilder>> componentBuilders();
```
because of the way multibinding works with dagger the map of component builders from the app scope will be included along with all of the user scope component builders. so your `getComponentBuilder` method can be modified to be something like this:
```java
@Override
public <ActivityType extends Activity, ComponentBuilderType extends ActivityComponentBuilder> ComponentBuilderType getComponentBuilder(Class<? extends ActivityType> key, Class<? extends ComponentBuilderType> builderType) {
    if (userComponent != null) {
        //TODO check implementation of the componentBuilders method, if it is expensive we should cache the result and drop that cached result with the userComponent inside of dropUserComponent
        return builderType.cast(userComponent.componentBuilders().get(key).get());
    }
    return builderType.cast(componentBuilders.get(key).get());
}
```

**Comment by jemshit** [comment]
Thanks for the answer, Fragment example is cool 👍 . 
I'm having difficulty in understating `UserComponent`. Does the way you explained assume some Activities are SubComponents of `Application`, and some Activities are SubComponents of `UserComponent` ? 
1) I think it is latter one, so my question is, are those SubComponent Activities of UserComponent can't be used without UserComponent is created ?
2) If we add `Map<Class<? extends Activity>, Provider<ActivityComponentBuilder>> componentBuilders();` into *UserComponentManager* instead of *UserComponent*, we will not need `UserComponent getUserComponent()` method anymore right?
3) Last question comes to my mind is, what is the way to have communication between sibling SubComponents? Like between Activity A and Activity B (they are both SubComponents of Application), can they have some kind of dependency from one to another?

Thanks

**Comment by trevjonez** [comment]
1: If the activity is something that should only be accessible while there is a user logged in than make it a sub component of the user component. Which means that you should have one user component active the whole time the user is logged in. In my implementations I typically have the application class manage the user component, this means that in my application on create I am also doing checks to restore the user component so they app can successfully start back up to the activity it was at if the system kills it.

2: That is an option you could go with, personally I view that map as a detail of the user component and not something the `UserComponentManager` should need to directly know about.

3: To enable cross activity communication you can expose an object from a super scope of the activity. Following your terms above, if activities A & B are both sub scopes of the User scope you can have the user component expose some type of communication interface type that activity A & B can then request be injected. I can see this being useful for inter-fragment communication but struggle to see how it would be used between activities since activities typically don't coexist at the same time.

My personal preference when I need this type of communication is to expose Rx observables of different events and request injection of the event observables that I need. I find this best because it doesn't require I define a certain comms interface I can just combine the streams in whatever way best fits the current needs.
